### ISSUE TITLE
type `t` is never mentioned in any of the function definitions

### ISSUE THREAD

**Issue by sichvoge** [petrochenko-pavel-a/typesystem#3]
[overview.md#Overview](https://github.com/petrochenko-pavel-a/typesystem/blob/master/org.raml.type.serialization.example/src/main/resources/overview.markdown#overview)

> For any valid type definition RAML provides a way to build a `serialize` and `deserialize` functions in a way when for every valid instance `i` of type `t` result of `deserialize(serialize(i,format),format)` is always deeply equal to `i` . Supported formats are json, xml, yaml as well as in memory representations of instances in programming languages which have support for representing structures, arrays, and scalars. We restrict constraints and serializations options to ensure that it is always possible for a valid type definitions.

I am not seeing any mentions of the type `t`, so why bother having it there?

**Comment by petrochenko-pavel-a** [comment]
agree
