### ISSUE TITLE
Are you missing some scalar types?

### ISSUE THREAD

**Issue by sichvoge** [petrochenko-pavel-a/typesystem#5]
The table in [overview.md#built-in-types](https://github.com/petrochenko-pavel-a/typesystem/blob/master/org.raml.type.serialization.example/src/main/resources/overview.markdown#built-in-types) clearly illustrates that there are five scalar types, but you mention only `number`, `string`, and `boolean` when describing the constraints for the built-in type `scalar`. Are you missing `file` and `date`?

Also, in some of these built-in types you mention that you can't inherit from it. Does that mean you can inherit from `scalar`?

**Comment by petrochenko-pavel-a** [comment]
>Also, in some of these built-in types you mention that you can't inherit from it. Does that mean you can >inherit from scalar?
yes, you can.

>Are you missing file and date?
Added some time ago

**Comment by sichvoge** [comment]
What would be a use case to inherit directly from `scalar`? In most cases I can think about you basically extend string or number, or others.
