### ISSUE TITLE
description for built-in type `integer` wrong?

### ISSUE THREAD

**Issue by sichvoge** [petrochenko-pavel-a/typesystem#7]
[overview.md#built-in-types](https://github.com/petrochenko-pavel-a/typesystem/blob/master/org.raml.type.serialization.example/src/main/resources/overview.markdown#built-in-types)

> `integer` - number type inherits from `integer` has extra requirement that instance should be integer

Does it really inherit from integer or do you mean `number`?

**Comment by sichvoge** [comment]
BTW, the following descriptions seem to be very strange as well:

> `boolean` - number type inherits from `scalar` but requires instance to be valid boolean
> `string` - number type inherits from `scalar` but requires instance to be valid string

both are number types?

**Comment by petrochenko-pavel-a** [comment]
>Does it really inherit from integer or do you mean number?
yep, thanks

>both are number types?
nope but scalar is every scalar (not object and not array)
